language: node_js
node_js: 8
os:
  - linux
  - osx
env:
  - npm_config_debug=yes
before_install: npm install -g node-gyp nyc
script:
  - nyc npm test && npm run test-ts
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild; fi