name: Prebuild

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, macos-latest, windows-2016]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: recursive
            - name: Use Node.js 10.x
              uses: actions/setup-node@master
              with:
                  node-version: 10.x
            - name: Prebuild
              run: |
                  npm ci
                  npm test
                  npm prebuild
              env:
                  CI: true
                  GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_AUTH_TOKEN}}
